### PR TITLE
Add architecture diagrams link to README.md

### PR DESCRIPTION
**Pull request by alexkarezin**
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/naverspringjdbcplus/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project.

In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful!

### CODE REVIEW

**Review by IAM20 — APPROVED** [review]
Cool! Thanks :)

**Comment by IAM20** [comment]
> [CLA assistant check](https://cla-assistant.io/naver/spring-jdbc-plus?pullRequest=100) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/naver/spring-jdbc-plus?pullRequest=100) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/naver/spring-jdbc-plus?pullRequest=100) it.

@alexkarezin May I ask for a CLA sign?

**Comment by alexkarezin** [comment]
Hi @IAM20 , I'm confused as to why the build is failing. Any chance you can take a look? Many thanks!

**Comment by IAM20** [comment]
@alexkarezin
I think it's probably because you didn't sign the CLA. [If possible, would it be okay to ask for a CLA signature?](https://cla-assistant.io/naver/spring-jdbc-plus?pullRequest=100)

**Comment by alexkarezin** [comment]
Oh, my bad. I got it!

**Pull request merged**
